### ISSUE TITLE
question about teams 

### ISSUE THREAD

**Issue by SolidGlade** [Toly65/UdonCombatSystem#11]
Hey I noticed there is a part to the combat systems that refers to teams?
but has been removed? or part of it has been removed from the prefab

any chance this will be added back in?
I don't so much want the start match part but would be like to be able to assign people to a team by pressing the button and have the visible marker above their head

**Comment by Toly65** [comment]
It'll be added back in in due time, twas a pain to make back in the day but I'll be adding it when I get round to it

**Comment by SolidGlade** [comment]
you are a legend 🙏
❤️

**Comment by SolidGlade** [comment]
for my needs it doesn't even need to refence the script. 
I just want a synced visible color or word above the players head when they click the button at the start :P

**Comment by Toly65** [comment]
trust me, just that is a lot harder than you think, I'll be getting round to it when I'm able to but currently, I'm doing a lot of background work for matchmaking systems in general

**Comment by SolidGlade** [comment]
I can imagine. hopefully its not to stressful 😄
