### ISSUE TITLE
Double Behaviors

### ISSUE THREAD

**Issue by Ainz41** [Toly65/UdonCombatSystem#15]
of course, SDK3, and Udon# latest version are in the same project,
and the only thing I did to use the asset was just put in the scene or prefab
however, in both of them, every object that have Udon behavior has another same script and that says,
"oh ho~ you might wanna convert me to Udon behavior haha"

look at that
![캡처](https://user-images.githubusercontent.com/60207969/174016449-f025d3bb-ac93-471f-8ed8-7531bdba6df7.PNG)

sometimes, it works for A bit, however most of the time it doesn't,
so I tried to use 5.0 of this asset, cuz maybe Udon# v0.20.3 have caused some error so
yeah there wasn't such thing in 5.0
and the disappointment of 5.0 was, here are people,
A B C D
A can hit B  D and,
B can hit A  D and,
C can hit A B D ----◀--◀---■
D can do all,----------------- ▲
someone can't hit someone ▲

guys who came for the test the asset, couldn't hit one of them who came in the map third
it's not like the hitbox of the third came guy doesn't follow him, i turned on the mesh of it so that we can see
so it was tracking him

i need some rescue

unity ver is 2019 4.31 f1

**Comment by Toly65** [comment]
as was explicitly written on 0.6 you must use udon# 1.0, not 0.20.3
you have to use the creator companion, available on the VRchat website to create a project or import the newer SDKS and udonsharp

**Comment by Ainz41** [comment]
anyway good to hear tho. hm... all of the sdk and udonsharp settings are going to be reset if i put that companion in it instead of there were, right?

**Comment by Ainz41** [comment]
> as was explicitly written on 0.6 you must use udon# 1.0, not 0.20.3 you have to use the creator companion, available on the VRchat website to create a project or import the newer SDKS and udonsharp
and i know it's quite dummy question tho, where could i get the udon# 1.0?
in github 0.203 is the latest one tho, and im sorry to ask tho, if i use the companion with 6.0 of yours then itd work nicely?

**Comment by Toly65** [comment]
creator companion is a seperate application that'll setup a project with the new SDK and udon#

**Comment by Ainz41** [comment]
thank you for responding, and yeah i was assuming so, thank you
-----Original Message-----
