### ISSUE TITLE
New players less than full health

### ISSUE THREAD

**Issue by SolidGlade** [Toly65/UdonCombatSystem#17]
If someone leaves with low health
seems like the next person joining gets the same health. so people aren't starting off with full hp

**Comment by Toly65** [comment]
I was about to say that's physically impossible due to health being stored locally but I figured out the issue, the hitbox manager has a variable that stores health and applies damage on deserialisation, so I'm just gonna set it to 0 whenever a player leaves

**Comment by Toly65** [comment]
issue should be fixed with 0.6.3, I would also recommend joining the discord

**Comment by SolidGlade** [comment]
Awesome 
Thankyou :)
