### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Cart00nHead** [Toly65/UdonCombatSystem#3]
Hey really sorry to message you 

But i have tried everything and i cant seem to get this prefab to work
Im using your demo scene but no damage is being Dealt everything seems to load in properly but when testing it even in game i no damage is given or received 

no errors in console, using the latest vrcsdk, udon sharp ect

**Comment by Toly65** [comment]
Ah yeah, unity fucked up the assignment of stuff on the hitboxes so they're
not communicating with the player health script, I'll push a fix out
