### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by SolidGlade** [Toly65/UdonCombatSystem#4]
Doesn't work,
Played around for a few hours but cant get it to work.
players don't appear to have any hit boxes, as they do not seem to be receiving damage at all

- Solid

**Comment by Toly65** [comment]
Are you using the latest release?

**Comment by SolidGlade** [comment]
yes sir

latest Sdk and udon# 

I load up the demo scene but nothing no dmg, i also drag and drop the prefab and still nothing. 
Doesn't have any errors in the console.

guns work fine but i cant damage or hurt the players and that health bar doesn't change 

Downloaded and re imported the unity file a few times in two different projects just to be sure 

- Solid

**Comment by Toly65** [comment]
The improved hitbox assigned keeps having its variables unassigned, the
issue is fixed now in the latest release(again)

**Comment by SolidGlade** [comment]
Hey mate
Thankyou for getting back to me.
unfortunately i for the life of me still can not get it to work. having tried your latest release 😅

Just the same issues previously mentioned

cheers Solid

**Comment by Blaixen** [comment]
Hey, yeah, so the prefab doesnt work. nothing works.

**Comment by Toly65** [comment]
in what way,

I've put the prefab into a blank project and it works fine

**Comment by Blaixen** [comment]
the raycasting doesn't work, im not sure if I'm doing something wrong, or its just not working

**Comment by Toly65** [comment]
![image](https://user-images.githubusercontent.com/88860967/150946495-eaf27c2d-6246-4cce-93d4-f40295d7c82f.png)
make sure that the sparkable and player layers are set appropriately, the current hitboxes are set on the default layer while your terrain might be on a different layer, thus sparkable needs to be different

**Comment by Blaixen** [comment]
Thanks, it works now!

**Comment by SolidGlade** [comment]
> Thanks, it works now!

your issue was the sparkable layers? I still cant get it to work for me tbh 😅
